# Generated by Django 5.2.7 on 2025-11-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
