# Generated by Django 5.2.7 on 2025-11-07 05:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_articulo_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_empresa', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='listaprecio',
            options={'ordering': ['-fecha_inicio', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='precio_1',
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='precio_2',
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='precio_3',
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='precio_4',
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='precio_costo',
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='canal_venta',
            field=models.IntegerField(blank=True, choices=[(1, 'Mostrador'), (2, 'Mayorista'), (3, 'Minorista'), (4, 'Online'), (5, 'Telefónico')], null=True),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='nombre',
            field=models.CharField(default='Lista de Precios', max_length=200),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Promocional'), (3, 'Especial')], default=1),
        ),
        migrations.AlterModelTable(
            name='listaprecio',
            table='listas_precios_nuevas',
        ),
        migrations.CreateModel(
            name='CombinacionProducto',
            fields=[
                ('combinacion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_minima_combinacion', models.PositiveIntegerField(default=1, help_text='Cantidad mínima de productos en la combinación')),
                ('cantidad_maxima_combinacion', models.PositiveIntegerField(blank=True, help_text='Cantidad máxima de productos en la combinación', null=True)),
                ('tipo_descuento', models.IntegerField(choices=[(1, 'Porcentaje'), (2, 'Monto Fijo')], default=1)),
                ('valor_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='combinaciones', to='core.articulo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='combinaciones', to='core.grupoarticulo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='combinaciones', to='core.lineaarticulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones_productos', to='core.listaprecio')),
            ],
            options={
                'db_table': 'combinaciones_productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='listas_precio', to='core.empresa'),
        ),
        migrations.CreateModel(
            name='PrecioArticulo',
            fields=[
                ('precio_articulo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ultimo_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('autorizado_bajo_costo', models.BooleanField(default=False)),
                ('descuento_proveedor', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento del proveedor (50-70%)', max_digits=5, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='precios_articulos', to='core.articulo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_articulos', to='core.listaprecio')),
            ],
            options={
                'db_table': 'precios_articulos',
            },
        ),
        migrations.CreateModel(
            name='DescuentoProveedor',
            fields=[
                ('descuento_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (50-70%)', max_digits=5)),
                ('monto_descuento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='descuentos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('precio_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_proveedor', to='core.precioarticulo')),
            ],
            options={
                'db_table': 'descuentos_proveedor',
                'ordering': ['-fecha_autorizacion'],
            },
        ),
        migrations.CreateModel(
            name='PrecioArticuloAntiguo',
            fields=[
                ('lista_precio_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_antiguos', to='core.articulo')),
            ],
            options={
                'db_table': 'listas_precios_antiguas',
                'ordering': ['-lista_precio_id'],
            },
        ),
        migrations.CreateModel(
            name='ReglaPrecio',
            fields=[
                ('regla_precio_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_regla', models.IntegerField(choices=[(1, 'Canal de Venta'), (2, 'Escala de Unidades'), (3, 'Escala de Monto'), (4, 'Combinación de Productos'), (5, 'Monto Total del Pedido')])),
                ('nombre', models.CharField(max_length=200)),
                ('prioridad', models.IntegerField(default=1, help_text='Prioridad de aplicación (menor número = mayor prioridad)')),
                ('canal_venta', models.IntegerField(blank=True, choices=[(1, 'Mostrador'), (2, 'Mayorista'), (3, 'Minorista'), (4, 'Online'), (5, 'Telefónico')], null=True)),
                ('cantidad_minima', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_total_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_total_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tipo_descuento', models.IntegerField(choices=[(1, 'Porcentaje'), (2, 'Monto Fijo')], default=1)),
                ('valor_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reglas_precio', to='core.articulo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reglas_precio', to='core.grupoarticulo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reglas_precio', to='core.lineaarticulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_precio', to='core.listaprecio')),
            ],
            options={
                'db_table': 'reglas_precios',
                'ordering': ['prioridad', 'tipo_regla'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('sucursal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_sucursal', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sucursales', to='core.empresa')),
            ],
            options={
                'db_table': 'sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='listas_precio', to='core.sucursal'),
        ),
        migrations.AddIndex(
            model_name='listaprecio',
            index=models.Index(fields=['empresa', 'sucursal', 'fecha_inicio', 'fecha_fin'], name='listas_prec_empresa_68860d_idx'),
        ),
        migrations.AddIndex(
            model_name='listaprecio',
            index=models.Index(fields=['estado', 'fecha_inicio', 'fecha_fin'], name='listas_prec_estado_bd2ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='combinacionproducto',
            index=models.Index(fields=['lista_precio', 'estado'], name='combinacion_lista_p_3a3cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='precioarticulo',
            index=models.Index(fields=['lista_precio', 'articulo'], name='precios_art_lista_p_df5b82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precioarticulo',
            unique_together={('lista_precio', 'articulo')},
        ),
        migrations.AddIndex(
            model_name='reglaprecio',
            index=models.Index(fields=['lista_precio', 'tipo_regla', 'estado'], name='reglas_prec_lista_p_1712e4_idx'),
        ),
        migrations.AddIndex(
            model_name='reglaprecio',
            index=models.Index(fields=['prioridad', 'estado'], name='reglas_prec_priorid_348b4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sucursal',
            unique_together={('empresa', 'codigo_sucursal')},
        ),
    ]
